# GitHub Sponsors Configuration
# See: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

# Supported platforms:
# - github: List of GitHub usernames
# - patreon: Patreon username
# - open_collective: Open Collective username
# - ko_fi: Ko-fi username
# - tidelift: Tidelift platform-name/package-name
# - community_bridge: Community Bridge project name
# - liberapay: Liberapay username
# - issuehunt: IssueHunt username
# - otechie: Otechie username
# - lfx_crowdfunding: LFX Crowdfunding project name
# - custom: List of custom sponsorship URLs

github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPENCOLLECTIVE_USERNAME
# ko_fi: YOUR_KOFI_USERNAME
# custom: ["https://www.paypal.me/YOUR_USERNAME", "https://www.buymeacoffee.com/YOUR_USERNAME"]
