blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Kl4rkx/free-iptv-player/tree/main/docs
    about: Check our comprehensive documentation for guides and tutorials
  - name: 💬 Discussions
    url: https://github.com/Kl4rkx/free-iptv-player/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/Kl4rkx/free-iptv-player/security/advisories/new
    about: Report security vulnerabilities privately (do not create public issues)
